version: '3'
services:
  nodejs:
    image: node:latest
    environment:
      NODE_ENV: development
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    working_dir: /app
    stdin_open: true
    tty: true
    command: sh -c "apt-get update && apt-get install -y sqlite3 && tail -f /dev/null"