version: '3.8'

services:
  node:
    container_name: node_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      NODE_ENV: development
    depends_on:
      - db

  db:
    container_name: sqlite_db
    image: alpine:latest
    volumes:
      - ./data:/data
    command: >
      sh -c "apk add sqlite && sqlite3 /data/database.sqlite"
